// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PopoffCrm.Infrastructure.Persistence;

#nullable disable

namespace PopoffCrm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PopoffCrmDbContext))]
    [Migration("20251211163216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogExcerpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DockerComposePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DockerProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontendUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique();

                    b.ToTable("Environments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4fa7483-59ae-4d0f-8ebd-0d0a0c6a1b44"),
                            ApiUrl = "https://test.latelina.popoff.com/api",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            DockerComposePath = "/opt/latelina-test/docker-compose.yml",
                            DockerProjectName = "latelina-test",
                            GitBranch = "develop",
                            IsDeleted = false,
                            IsProduction = false,
                            Name = "Test",
                            ProjectId = new Guid("c0aa483c-f17e-47a1-98dc-8b5e0c9cba10"),
                            ServerId = new Guid("6f7f8455-43c2-4b61-86a3-a0c24b5c7d77"),
                            Slug = "test"
                        },
                        new
                        {
                            Id = new Guid("832a84f0-5d6d-4f1b-8d96-7716b7a6c1a0"),
                            ApiUrl = "https://latelina.popoff.com/api",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            DockerComposePath = "/opt/latelina-prod/docker-compose.yml",
                            DockerProjectName = "latelina-prod",
                            GitBranch = "main",
                            IsDeleted = false,
                            IsProduction = true,
                            Name = "Prod",
                            ProjectId = new Guid("c0aa483c-f17e-47a1-98dc-8b5e0c9cba10"),
                            ServerId = new Guid("6f7f8455-43c2-4b61-86a3-a0c24b5c7d77"),
                            Slug = "prod"
                        });
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.HealthCheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("HealthCheckResults");
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0aa483c-f17e-47a1-98dc-8b5e0c9cba10"),
                            Code = "LTLNA",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latelina project",
                            IsDeleted = false,
                            Name = "Latelina"
                        });
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f7f8455-43c2-4b61-86a3-a0c24b5c7d77"),
                            ConnectionType = "LocalShell",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hetzner production server",
                            HostName = "Hetzner-Prod-1",
                            IpAddress = "192.168.1.1",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hetzner-Prod-1"
                        });
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4f1bf76-df8a-4b77-9e74-8e5898dd34b8"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Petar Popov",
                            Email = "admin@popoffcrm.com",
                            IsDeleted = false,
                            PasswordHash = "10000.D73617EBFC538BD6ED61FB63D075601C.3E92952FDA90A4D3BB7CCB80A6D38DDB17AEA347E520408CF8A4B4CF9D892457",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Deployment", b =>
                {
                    b.HasOne("PopoffCrm.Domain.Entities.Environment", "Environment")
                        .WithMany("Deployments")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopoffCrm.Domain.Entities.User", "RequestedByUser")
                        .WithMany("Deployments")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Environment", b =>
                {
                    b.HasOne("PopoffCrm.Domain.Entities.Project", "Project")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopoffCrm.Domain.Entities.Server", "Server")
                        .WithMany("Environments")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.HealthCheckResult", b =>
                {
                    b.HasOne("PopoffCrm.Domain.Entities.Environment", "Environment")
                        .WithMany("HealthChecks")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Environment", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("HealthChecks");
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Project", b =>
                {
                    b.Navigation("Environments");
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.Server", b =>
                {
                    b.Navigation("Environments");
                });

            modelBuilder.Entity("PopoffCrm.Domain.Entities.User", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
